### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by miimote** [kitech/qt.go#12]
Hi,
I ve compiled the basic example showing a labeled button. It compiles and runs well but not showing button text.

**Comment by di3663** [comment]
which language are you using?
![default](https://user-images.githubusercontent.com/36250009/37008702-59e37574-211e-11e8-96dc-77f45756033f.PNG)

**Comment by miimote** [comment]
This issue was for my previous system (Ubuntu 16.4). Now in archlinux woks well.
![imagen](https://user-images.githubusercontent.com/11861110/37791984-d6dac912-2e0a-11e8-82e8-e6758240fb2e.png)
