### ISSUE TITLE
QML error: module not installed

### ISSUE THREAD

**Issue by GeertJohan** [kitech/qt.go#15]
I'm getting an error when running a QML project using qt.go. I've tried several things to debug and fix the problem but cannot find the correct solution.

When I run a qml file, either using my own binary or using `go-qmlviewer`, the qml engine prints these errors to output:

```
qrc:///qml/tune.qml:4 module "QtQuick.Window" is not installed
qrc:///qml/tune.qml:1 module "QtQuick" is not installed
qrc:///qml/tune.qml:3 module "QtQuick.Layouts" is not installed
qrc:///qml/tune.qml:5 module "QtQuick.Templates" is not installed
qrc:///qml/tune.qml:2 module "QtQuick.Controls" is not installed
… etc …
```

Am I missing something obvious here?
Could it be that these modules aren't properly registered to Qt because this project uses libffi? Or perhaps is my libQt5inline.so wrong or missing the modules in it?

I hope we can find a solution because I really want to try out and work with QML for rendering a UI in Go.

**Comment by kitech** [comment]
I think it's not related to go-qmlviewer or qt.go or libQt5Inline.
Seems you lack of some qt's .qml file.
Did you installed all qt's modules like qt5-declarative, qt5-quick, qt5-quickcontrols2?

I must sorry to say, this command is a clone of qt's `qmlscene` command, I found `qmlscene` after add myself `qmlviewer`. You can use `qmlscene` for test your .qml file.

**Comment by kitech** [comment]
Did you put qml in .qrc file?
Use go-uic to compile .qrc to .go source first.
