### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by 1377195627** [kitech/qt.go#20]
![image](https://user-images.githubusercontent.com/8142265/39403980-7aecf8b8-4bbb-11e8-97f5-63ffbd7fbce4.png)

![image](https://user-images.githubusercontent.com/8142265/39403979-714db6b2-4bbb-11e8-8f45-71c67cf5e81d.png)
加入环境变量后

![image](https://user-images.githubusercontent.com/8142265/39403975-615702cc-4bbb-11e8-936b-59112719890d.png)

**Comment by 1377195627** [comment]
ffi 3.2.1 的头文件位置在3.3中修正了。但是现在还是rc版，arch只能从aur中装git版，请修正readme.md

**Comment by kitech** [comment]
需要更详细的诊断信息，
go build -v -x的输出
第二个需要 cgo.a的权限，这就是其他问题
我这archlinux不需要用aur包，挺正常的。

**Comment by kitech** [comment]
https://studygolang.com/articles/436

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/39405784-7bca8516-4bde-11e8-86c5-81eaae91473e.png)
两个头文件的位置不同，3.2.1的位置好像会让cgo找不到头文件

**Comment by kitech** [comment]
不会的，这个早就处理过了
要是这步都过不了，我自己这真都是没法测试了。
都安装了话，最好别用串了。

**Comment by 1377195627** [comment]
神奇，吧git卸了换会3.2.1又可以了，不过git的有毒，装了后libinput居然会去加载libffi.so.6,而git版是.7，然后x就boom了

**Comment by kitech** [comment]
又是个不知所以的问题？
