### ISSUE TITLE
when i build and run the sample got error

### ISSUE THREAD

**Issue by KiVixx** [kitech/qt.go#28]
i can build the sample , but when i run the sample , got this problem. 
MacBook-Pro:~ kisker$ LD_LIBRARY_PATH=/usr/local/opt/qt/lib ./button
2018/09/19 07:34:22 ffi_invoke.go:177: dl: dlopen(libQt5Inline.dylib, 2): image not found {handle:{c:<nil>}}
2018/09/19 07:34:22 ffi_invoke.go:345: Symbol not found: QDynSlotObject_new

**Comment by kitech** [comment]
good.
libQt5Inline is bridge between qt.go and qt. if u have not install it, donwload here and decompress and put in /usr/local/opt/qt/lib for preview, https://github.com/kitech/qt.inline/releases
