### ISSUE TITLE
Kneel for Windows to compile qt.go

### ISSUE THREAD

**Issue by wrzfeijianshen** [kitech/qt.go#29]
I look at the install.md，Do not know how to operate in Windows, the document is not too detailed, do not know how to do, can steps in detail, or other related documents, for example
https://github.com/therecipe/qt/wiki/Installation-on-Windows
This is a little bit more detailed,
Please kneel and ask for your help。

**Comment by kitech** [comment]
Did you looked at the `windows` section of https://github.com/kitech/qt.go/blob/master/install.md ?
There is a binary dependecy package all qt.go needed. Only `git clone`.
Then can use `go get` `go build` for qt.go and examples.

**Comment by wrzfeijianshen** [comment]
https://github.com/kitech/qt.go/issues/5
