### ISSUE TITLE
疑似弃坑？

### ISSUE THREAD

**Issue by xiayesuifeng** [kitech/qt.go#30]
多月不见貌似还没支持自定义信号槽

**Comment by a97077088** [comment]
> 多月不见貌似还没支持自定义信号槽

老铁我也是受不了therecipe/qt的编译速度，不过我可以使用他的go build

**Comment by xiayesuifeng** [comment]
> > 多月不见貌似还没支持自定义信号槽
> 
> 老铁我也是受不了therecipe/qt的编译速度，不过我可以使用他的go build

第一次go build有时候很慢，但是之后的速度还行

**Comment by a97077088** [comment]
你的qq是多少，交流下

**Comment by kitech** [comment]
弃坑是不会弃的吧。
看readme.md, custom signal试验支持：
https://github.com/kitech/qt.go/blob/master/docs/qt_meta_data_mark_syntax_for_go.md
https://github.com/kitech/qt.go/blob/master/qtmeta/tests/meta_data_test_.go

**Comment by kitech** [comment]
> 你的qq是多少，交流下

快交流

**Comment by a97077088** [comment]
97077088

**Comment by a97077088** [comment]
这玩意能编译static吗

**Comment by kitech** [comment]
这有发布的静态编译qt的了，到这找带static字样的包，https://github.com/kitech/qt.inline/releases/
然后希望静态到什么程度，允许带哪些dll，可以自己编译。参考：https://github.com/kitech/qt.inline/blob/master/run-mingw.sh

**Comment by kitech** [comment]
> @kitech 大哥，有qq不，交流下吗

不如建个QQ交流群？

**Comment by kitech** [comment]
现在想建个qq群好难。

**Comment by xiayesuifeng** [comment]
来用tg不好吗，我有个qt群

**Comment by xiayesuifeng** [comment]
不过这个库能用go mod吗。那个qt库太大死活用不了

**Comment by a97077088** [comment]
群多少

**Comment by kitech** [comment]
我建不了，老失败，能转个给我吗

**Comment by kitech** [comment]
好了，qq群：933636020

**Comment by xiayesuifeng** [comment]
https://t.me/qtdevjiaoliu
为何你们要坚持垃圾qq，tg多好

**Comment by kitech** [comment]
tg链接保留着吧，听说不是网络不稳定吗，而且我没有账号。

**Comment by xiayesuifeng** [comment]
都是用go的人了。不自备梯子能好好go get？

**Comment by kitech** [comment]
这个事，说的就是这个事，毕竟不是直连，有些环境还是能直连最好了

**Comment by xiayesuifeng** [comment]
iptables+透明代理不是很舒服吗。。。

**Comment by kitech** [comment]
tg有两个问题被我弃了，一个是不能直连，一个是手机号注册。如果非用开源的（国外的）我可能会选用用matrix.org
