### ISSUE TITLE
Where can I find go-uic or build a version of it?

### ISSUE THREAD

**Issue by avikio** [kitech/qt.go#32]
Hi

Where can I find a compiled version of go-uic?
If it does not exist how can I build it?
I tried to build and use qt.go\go-uic\main.go but the output is just empty.
I also tried to build qt.go\go-uic\tuic.go but it doesn't build.

Thanks for your help

**Comment by kitech** [comment]
seems you havn't 'cmd' directory, check if updated to git head?

     cd $GOPATH/github.com/kitech/qt.go 
then,
```
        go build -v -o bin/go-uic ./cmd/go-uic
        go build -v -o bin/go-rcc ./cmd/go-rcc
```

-o argument is optional.
