### ISSUE TITLE
go_uic 解析问题

### ISSUE THREAD

**Issue by zoocke** [kitech/qt.go#33]
1 this.EdiTest.SetEchoMode(this.QLineEdit::Password)  //Error this.QLineEdit::Password
2 this.Menubar.AddAction(this.Menu->MenuAction()) //Error this.Menu->MenuAction()
3 this.Menu.AddAction(this.ConnDB)                            //Error this.ConnDB
4 this.WidMain.SetStyleSheet(this.QStringLiteral(""))    //widMain  *qtwidgets.QTabWidget
                                                                                       //Error this.QStringLiteral("")
5 this.WidMain.SetUsesScrollButtons(this.False)            //Error this.False
6 this.TableWork.SetAutoScroll(this.True)                       //Error this.True  
                                                                                        //TableWork *qtwidgets.QTableWidget
7 this.TableWork.SetCornerButtonEnabled(this.True)     //Error this.True
8 this.WidDict.SetStyleSheet(this.QStringLiteral("Background-Color: Rgb(255, 255, 255);"))
                                                                                        //Error this.QStringLiteral
                                                                                        //WidDict *qtwidgets.QListWidget
9 this.WidDict.SetDragEnabled(this.True)                       //Error this.True

**Comment by kitech** [comment]
https://github.com/kitech/qt.go/commit/2f93864a3b82a1a9a38bc363021040fed7e1c967
