### ISSUE TITLE
go-uic  Menu,Menubar 更改

### ISSUE THREAD

**Issue by zoocke** [kitech/qt.go#35]
1 this.Menu.AddAction
2 this.Menubar.AddAction

改：
this.Menu.QWidget.AddAction
this.Menubar.QWidget.AddAction

**Comment by kitech** [comment]
这是什么意思，不这样改碰到什么问题吗？

**Comment by kitech** [comment]
should be fixed: https://github.com/kitech/qt.go/commit/db41762fcf1ea8bdb166d5cf886b1184bc0b43d1
