### ISSUE TITLE
关于Label标签的两个不能显示的问题

### ISSUE THREAD

**Issue by wrzfeijianshen** [kitech/qt.go#36]
1.环境 : qt5.12,windows10
2.操作:用Qt Designer 创建widget.ui.并添加一个标签.生成.go文件后.在man.go中添加以下代码
2.1 : 问题1 : "添加富文本,img路径本地路径还是网络路径皆不能显示图片,代码如下
```
strText1 := "<html><body> <img src=\"https://csdnimg.cn/pubfooter/images/csdn-kf.png\" width=\"100\" height=\"100\" /> </body> </html>"
mw.Label.SetText(strText1)
```
2.2 问题2:  关于qabel 动画,在qt代码中可以显示,代码变成go就显示不了.代码如下.
```
var pMovie *qtgui.QMovie
pMovie = pMovie.NewForInherit2p("d:\\zb.gif")
mw.PLabel.SetMovie(pMovie)
mw.PLabel.SetFixedSize1(125, 125)
mw.PLabel.SetScaledContents(true)
pMovie.Start()
```

**Comment by kitech** [comment]
linux上确定问题2, linux上没问题，正常播放本地gif动画
可能的问题，目前提供的打包的windows上的qt5inline.dll可能没有gif格式支持

**Comment by kitech** [comment]
linux上确定问题1, 不能正常显示网络图片。
但是能够正常显示本地图片（把链接换本地路径），记得应该同样支持qrc资源图片。

在qt-designer中也无法正常显示。
是否是不支持网络资源呢？不过还没跑C++测试。

**Comment by kitech** [comment]
测试代码：https://github.com/qtchina/qt.go.demos/issue36/

**Comment by kitech** [comment]
这个应该修复gif不能显示的问题，https://github.com/kitech/qt.inline/commit/be9aad768674f155b3c98f0a68bb8e7c421695d8
