### ISSUE TITLE
使用macos下生成的go-rcc依赖libQt5Inline.dylib

### ISSUE THREAD

**Issue by easykoo** [kitech/qt.go#39]
$ go-rcc rcc.qrc
2019/02/02 19:56:48 ffi_invoke.go:180: dl: dlopen(libQt5Inline.dylib, 2): image not found {handle:{c:<nil>}}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x4366e1a, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42b5c70, 0xc0000c1c68, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0000c1c30 sp=0xc0000c1bf8 pc=0x400544e
github.com/kitech/qt.go/qtrt._C2func_ffi_call_ex(0x0, 0xe, 0xc0000960a8, 0x5, 0xc0000b00c0, 0xc0000ca000, 0x0, 0x0)
	_cgo_gotypes.go:178 +0x4d fp=0xc0000c1c68 sp=0xc0000c1c30 pc=0x4105e3d
github.com/kitech/qt.go/qtrt.InvokeQtFunc6.func1(0x0, 0xc00000000e, 0xc0000960a8, 0xc000000005, 0xc0000b00c0, 0xc0000ca000, 0xc0000ca000, 0x14)
	/Users/wangcheng/workspace/go/src/github.com/kitech/qt.go/qtrt/ffi_invoke.go:283 +0x88 fp=0xc0000c1cb8 sp=0xc0000c1c68 pc=0x410d348
github.com/kitech/qt.go/qtrt.InvokeQtFunc6(0x435e092, 0x12, 0x42e900e, 0xc0000c1ea0, 0x5, 0x5, 0xc000090360, 0x3, 0x435ae38)
	/Users/wangcheng/workspace/go/src/github.com/kitech/qt.go/qtrt/ffi_invoke.go:283 +0x154 fp=0xc0000c1e28 sp=0xc0000c1cb8 pc=0x410a8b4
github.com/kitech/qt.go/qtrt.NewQDynSlotObject(0x435e78c, 0x13, 0x0, 0x0)
	/Users/wangcheng/workspace/go/src/github.com/kitech/qt.go/qtrt/qdynslotobject.go:43 +0x164 fp=0xc0000c1f00 sp=0xc0000c1e28 pc=0x410c224
github.com/kitech/qt.go/qtrt.init_destroyedDynSlot()
	/Users/wangcheng/workspace/go/src/github.com/kitech/qt.go/qtrt/qdynslotobject.go:235 +0x3f fp=0xc0000c1f30 sp=0xc0000c1f00 pc=0x410c47f
github.com/kitech/qt.go/qtrt.init.2()
	/Users/wangcheng/workspace/go/src/github.com/kitech/qt.go/qtrt/ffi_invoke.go:171 +0x42 fp=0xc0000c1f48 sp=0xc0000c1f30 pc=0x410a0f2
github.com/kitech/qt.go/qtrt.init()
	<autogenerated>:1 +0x47f fp=0xc0000c1f80 sp=0xc0000c1f48 pc=0x410dcff
main.init()
	<autogenerated>:1 +0x6e fp=0xc0000c1f98 sp=0xc0000c1f80 pc=0x42b595e
runtime.main()
	/usr/local/go/src/runtime/proc.go:189 +0x1bd fp=0xc0000c1fe0 sp=0xc0000c1f98 pc=0x402e3dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000c1fe8 sp=0xc0000c1fe0 pc=0x4059001

**Comment by kitech** [comment]
should fixed
