### ISSUE TITLE
windows下生成go-rcc失败

### ISSUE THREAD

**Issue by easykoo** [kitech/qt.go#40]
Z:\workspace\go\src>go get -v -u github.com/kitech/qt.go/cmd/go-rcc
github.com/kitech/qt.go (download)
github.com/kitech/dl (download)
github.com/emirpasic/gods (download)
github.com/kitech/goplusplus (download)
github.com/Workiva/go-datastructures (download)
github.com/bitly/go-simplejson (download)
github.com/cheekybits/genny (download)
github.com/huandu/xstrings (download)
github.com/lytics/base62 (download)
github.com/pkg/errors (download)
github.com/kitech/goplusplus
# github.com/kitech/goplusplus
github.com\kitech\goplusplus\intern.go:17:10: undefined: syscall.Stat_t

**Comment by kitech** [comment]
thx, should fixed https://github.com/kitech/goplusplus/commit/3f221dc5bd187027f00eb825f49d28cc765fe5b3
