### ISSUE TITLE
kitech/qt.go/cmd/qt-uic 編譯會出現錯誤

### ISSUE THREAD

**Issue by MarkCL** [kitech/qt.go#41]
kitech/qt.go/cmd/qt-uic/main.go 編譯會出現下列錯誤：

load github.com/kitech/qt.go.bak/miscutil: cannot find module providing package github.com/kitech/qt.go.bak/miscutil

看了一下kitech/qt.go/cmd/qt-uic/main.go裡面似乎是import miscutil路徑多了.bak~

**Comment by kitech** [comment]
是的，开发环境目录的问题

已经提交修复
