### ISSUE TITLE
qt.go项目名称是否要避免混淆？

### ISSUE THREAD

**Issue by kerneltravel** [kitech/qt.go#42]
X:\dev\gotest>go get -v github.com/kitech/qt.go
CreateFile github.com/kitech/qt.go: The system cannot find the path specified.

我在windows下配置好环境变量和go等的依赖库的时候，执行go  get -v  github.com/kitech/qt.go
，遇到以上报错。

但执行 go get  -v  github.com/kitech/dl  和其他go get 例如go get -v github.com/astaxie/beego  ，是成功的。

所以判断是qt.go 这个项目名被go  当成了路径下的go代码文件。

不知道大家有没有遇到这样的情况，是否因为qt.go 项目名导致的混淆bug ？

**Comment by kitech** [comment]
谢谢反馈

试了一下最新go版本，在linux系统上正常使用。还需要在看具体是windows系统引起的，或者是go windows版本引起的。

名字的话还要考虑，一时不能改的情况下，windows上可以先手动 git clone 到GOPATH目录。

**Comment by kerneltravel** [comment]
感谢！经过测试，windows上可以先手动 git clone 到GOPATH目录，然后进入项目代码目录go build，就可以编译成功了，得到的效果跟go get 项目的效果一样。
